
services:
  db:
    image: postgres:15
    container_name: projeto-saude-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saude
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: projeto-saude-app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: bash -c "python src/generate_data.py && streamlit run src/app.py"
    ports:
      - "8501:8501"